# Generated by Django 3.0.8 on 2020-10-12 01:10

from django.db import migrations, models
import pandas as pd
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
fixture_dir = os.path.abspath(os.path.join(BASE_DIR, '../fixture.data'))
censusdata_filename = os.path.join(fixture_dir, 'CensusData.csv')


def load_fixture(apps, schema_editor):
    MyModel = apps.get_model("covid19", "censusdata")
    db_alias = schema_editor.connection.alias

    df = pd.read_csv(censusdata_filename, delimiter=',')
    data = []

    for index, row in df.iterrows():
        data.append(MyModel(
            geocodeid = row.GeoCodeID,
            population = row.Population,
            density = row.Density)
        )
    MyModel.objects.using(db_alias).bulk_create(data)

def unload_fixture(apps, schema_editor):
    "Brutally deleting all entries for this model..."

    MyModel = apps.get_model("covid19", "censusdata")
    MyModel.objects.all().delete()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='censusdata',
            fields=[
                ('geocodeid', models.IntegerField(primary_key=True, serialize=False, verbose_name='geographic code identifier')),
                ('population', models.IntegerField(verbose_name='Population')),
                ('density', models.FloatField(null=True, verbose_name='Population density')),
            ],
        ),
        migrations.RunPython(load_fixture, reverse_code=unload_fixture),
    ]
